# conda env create -f environment.yml
name: random-phase-approximation

channels:
- conda-forge

dependencies:
  # general numerics (version controlled)
  - python=3.7*
  - numpy=1.16*
  - scipy=1.2*
  # plotting and serialization
  - matplotlib=3.1*
  - seaborn
  - ipympl  # interactive plotting in jupyterlab
  # jupyter tools and extensions
  - jupyterlab
  - voila=0.1.9
  - nodejs
  - jupytext
  - line_profiler
  # other
  - unyt=2.2*
  - signac=1.2*
  - signac-dashboard=0.2*
  - signac-flow=0.7*
  - jinja2=2.10*
  - ffmpeg=4.1*
  - pandas
  - pytables
  - pytest-flakes
  - sympy
  - gunicorn
  # dev tools
  - black
  - pip
  - setuptools
  - wheel
  - pre_commit
  - pip:
    - matplotlib-label-lines

