# make -Bnd | grep "Pruning file" | sort | uniq

    Pruning file 'base.h'.
    Pruning file 'bin.h'.
    Pruning file 'binom.cc'.
    Pruning file 'binomh.cc'.
    Pruning file 'common.h'.
    Pruning file 'edmonds.h'.
    Pruning file 'eigenval.cc'.
    Pruning file 'eigenval.h'.
    Pruning file 'excstr.cc'.
    Pruning file 'funk.cc'.
    Pruning file 'funk.h'.
    Pruning file 'gfv.cc'.
    Pruning file 'incanon.cc'.
    Pruning file 'init.cc'.
    Pruning file 'isospin.cc'.
    Pruning file 'lorneu.cc'.
    Pruning file 'matcon0.cc'.
    Pruning file 'matcons.cc'.
    Pruning file 'mbin.cc'.
    Pruning file 'mbout.cc'.
    Pruning file 'mesh.h'.
    Pruning file 'mjin.cc'.
    Pruning file 'mjout.cc'.
    Pruning file 'mout.cc'.
    Pruning file 'msym.cc'.
    Pruning file 'multred.cc'.
    Pruning file 'nrcfunk.cc'.
    Pruning file 'nr.h'.
    Pruning file 'nrutil.h'.
    Pruning file 'pair.cc'.
    Pruning file 'paramet.cc'.
    Pruning file 'potdif.cc'.
    Pruning file 'prepint.cc'.
    Pruning file 'qpbess.cc'.
    Pruning file 'qplevel.cc'.
    Pruning file 'qpmataph.cc'.
    Pruning file 'qpmatapp.cc'.
    Pruning file 'qpmatbph.cc'.
    Pruning file 'qpmatbpp.cc'.
    Pruning file 'qpmatpair.cc'.
    Pruning file 'qppairout.cc'.
    Pruning file 'racah.cc'.
    Pruning file 'racahs.cc'.
    Pruning file 'radialfg.cc'.
    Pruning file 'relqrpa.cc'.
    Pruning file 'rpa.cc'.
    Pruning file 'rpaprobe.cc'.
    Pruning file 'rpasort.cc'.
    Pruning file 's9jslj.cc'.
    Pruning file 'sla.h'.
    Pruning file 'testint.cc'.
    Pruning file 'trans.cc'.
    Pruning file 'transcur.cc'.
    Pruning file 'vphcomp.cc'.
    Pruning file 'vphfgm.cc'.
    Pruning file 'wigner.cc'.
    Pruning file 'wph.cc'.
